/**
 * Cloudflare Worker Proxy for Supabase (Edge Functions + Auth)
 * 
 * This worker proxies requests from your custom domain (e.g., api.yourdomain.com)
 * to your Supabase project (e.g., xyzabc123.supabase.co)
 * 
 * Supports:
 * - Edge Functions: /functions/v1/*
 * - Auth endpoints: /auth/v1/*
 * - All other Supabase endpoints
 * 
 * This allows you to use a custom domain without paying for Supabase Pro tier.
 */

interface Env {
  SUPABASE_URL: string
  SUPABASE_ANON_KEY: string
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, apikey, x-client-info',
  'Access-Control-Max-Age': '86400',
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS_HEADERS })
    }

    try {
      const url = new URL(request.url)
      let targetPath = url.pathname
      
      // Handle different Supabase endpoints
      // If path starts with /functions/v1, /auth/v1, /rest/v1, or /storage/v1, use as-is
      // Otherwise, assume it's an Edge Function and prepend /functions/v1
      if (!targetPath.startsWith('/functions/v1') && 
          !targetPath.startsWith('/auth/v1') && 
          !targetPath.startsWith('/rest/v1') && 
          !targetPath.startsWith('/storage/v1')) {
        // Assume it's an Edge Function - prepend /functions/v1
        const functionName = targetPath.replace(/^\//, '')
        targetPath = `/functions/v1/${functionName}`
      }
      
      // For OAuth authorize, replace redirect_uri in query params if it contains Supabase domain
      let searchParams = new URLSearchParams(url.search)
      if (targetPath === '/auth/v1/authorize' && searchParams.has('redirect_to')) {
        // redirect_to is the callback URL in our app, not the OAuth redirect_uri
        // The OAuth redirect_uri is generated by Supabase based on its configuration
        // We can't change it here, but we'll handle it in the response
      }
      
      // Build target URL
      const targetUrl = `${env.SUPABASE_URL}${targetPath}${url.search}`

      // Prepare headers
      const headers = new Headers(request.headers)
      
      // Set Supabase API key
      headers.set('apikey', env.SUPABASE_ANON_KEY)
      
      // Preserve Authorization header if present (for authenticated requests)
      // If Authorization header exists, keep it; otherwise, set Bearer token
      if (!headers.has('Authorization')) {
        headers.set('Authorization', `Bearer ${env.SUPABASE_ANON_KEY}`)
      }
      
      // Remove Host header to avoid conflicts
      headers.delete('Host')
      
      // Forward the request to Supabase
      const response = await fetch(targetUrl, {
        method: request.method,
        headers,
        body: request.body,
      })

      // Clone response to modify headers and body
      const responseHeaders = new Headers(response.headers)
      let modifiedBody: string | ReadableStream<Uint8Array> | null = null
      
      // For OAuth authorize endpoint, replace Supabase domain with proxy domain
      if (targetPath === '/auth/v1/authorize') {
        // Handle redirect responses (3xx status codes)
        if (response.status >= 300 && response.status < 400) {
          const location = responseHeaders.get('Location')
          if (location) {
            try {
              const locationUrl = new URL(location)
              // If Location contains Supabase domain in redirect_uri, replace it with proxy domain
              if (locationUrl.searchParams.has('redirect_uri')) {
                const redirectUri = locationUrl.searchParams.get('redirect_uri')!
                const redirectUriUrl = new URL(redirectUri)
                if (redirectUriUrl.hostname.includes('supabase.co')) {
                  // Replace Supabase domain with proxy domain
                  redirectUriUrl.hostname = url.hostname
                  redirectUriUrl.protocol = url.protocol
                  locationUrl.searchParams.set('redirect_uri', redirectUriUrl.toString())
                  responseHeaders.set('Location', locationUrl.toString())
                }
              }
            } catch (e) {
              console.error('Error parsing Location header:', e)
            }
          }
        }
        
        // Get content type first
        const contentType = responseHeaders.get('Content-Type') || ''
        
        // Only read body once - clone response if we need to read it
        if (response.status === 200 && (contentType.includes('application/json') || contentType.includes('text/html'))) {
          try {
            // Clone response to read body without consuming original
            const clonedResponse = response.clone()
            const bodyText = await clonedResponse.text()
            
            if (contentType.includes('application/json')) {
              // Handle JSON responses (Supabase returns OAuth URL in JSON body)
              try {
                const bodyJson = JSON.parse(bodyText)
                
                // If response contains 'url' field with Supabase domain, replace it
                if (bodyJson.url && typeof bodyJson.url === 'string') {
                  const oauthUrl = new URL(bodyJson.url)
                  
                  // Always add prompt=select_account to Google OAuth URLs
                  if (oauthUrl.hostname === 'accounts.google.com') {
                    oauthUrl.searchParams.set('prompt', 'select_account')
                  }
                  
                  // Replace Supabase domain in redirect_uri parameter
                  if (oauthUrl.searchParams.has('redirect_uri')) {
                    const redirectUri = oauthUrl.searchParams.get('redirect_uri')!
                    const redirectUriUrl = new URL(redirectUri)
                    if (redirectUriUrl.hostname.includes('supabase.co')) {
                      // Replace Supabase domain with proxy domain
                      redirectUriUrl.hostname = url.hostname
                      redirectUriUrl.protocol = url.protocol
                      oauthUrl.searchParams.set('redirect_uri', redirectUriUrl.toString())
                    }
                  }
                  
                  bodyJson.url = oauthUrl.toString()
                  modifiedBody = JSON.stringify(bodyJson)
                }
              } catch (e) {
                // If JSON parsing fails, use original body
                console.error('Error parsing JSON response:', e)
              }
            } else if (contentType.includes('text/html')) {
              // Handle HTML responses (Supabase may return HTML with OAuth form)
              // IMPORTANT: Don't modify Google's OAuth form HTML - it breaks the form
              // Only modify redirect_uri in query strings, not in JavaScript or form attributes
              const supabaseDomain = env.SUPABASE_URL.replace('https://', '').replace('http://', '')
              const proxyDomain = url.hostname
              
              // Only modify redirect_uri in URL query strings (not in JavaScript or form attributes)
              // Pattern: ?redirect_uri=https://xyz.supabase.co/auth/v1/callback&...
              // or &redirect_uri=https://xyz.supabase.co/auth/v1/callback
              let modifiedText = bodyText
              
              // Replace redirect_uri in query strings only (very specific pattern)
              modifiedText = modifiedText.replace(
                new RegExp(`([?&]redirect_uri=)(https?://[^"'\s&<>]*?)${supabaseDomain.replace(/\./g, '\\.')}([^"'\s&<>]*)`, 'gi'),
                (match, prefix, before, after) => {
                  try {
                    const redirectUriUrl = new URL(`${before}${supabaseDomain}${after}`)
                    redirectUriUrl.hostname = proxyDomain
                    redirectUriUrl.protocol = url.protocol
                    return `${prefix}${redirectUriUrl.toString()}`
                  } catch (e) {
                    console.error('Error replacing redirect_uri in query:', e)
                    return match
                  }
                }
              )
              
              // Replace URL-encoded redirect_uri in query strings
              modifiedText = modifiedText.replace(
                new RegExp(`([?&]redirect_uri=)([^"'\s&<>]*)`, 'gi'),
                (match, prefix, encoded) => {
                  try {
                    const decoded = decodeURIComponent(encoded)
                    if (decoded.includes(supabaseDomain) && decoded.startsWith('http')) {
                      const redirectUriUrl = new URL(decoded)
                      redirectUriUrl.hostname = proxyDomain
                      redirectUriUrl.protocol = url.protocol
                      return `${prefix}${encodeURIComponent(redirectUriUrl.toString())}`
                    }
                  } catch (e) {
                    // Not URL-encoded or doesn't contain Supabase domain, skip
                  }
                  return match
                }
              )
              
              // Replace Supabase domain in text content (for "to continue to" message) - but be careful
              // Only replace in specific contexts, not in JavaScript
              modifiedText = modifiedText.replace(
                new RegExp(`(Przejdź do aplikacji |to continue to |Go to application )${supabaseDomain.replace(/\./g, '\\.')}`, 'gi'),
                (match, prefix) => {
                  return `${prefix}${proxyDomain}`
                }
              )
              
              if (modifiedText !== bodyText) {
                modifiedBody = modifiedText
              }
            }
          } catch (e) {
            console.error('Error parsing response body:', e)
          }
        }
      }
      
      // Add CORS headers to response
      for (const [key, value] of Object.entries(CORS_HEADERS)) {
        responseHeaders.set(key, value)
      }

      return new Response(modifiedBody || response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: responseHeaders,
      })
    } catch (error) {
      console.error('Proxy error:', error)
      return new Response(
        JSON.stringify({ 
          error: 'Proxy error', 
          message: error instanceof Error ? error.message : 'Unknown error' 
        }),
        { 
          status: 500, 
          headers: { 
            ...CORS_HEADERS,
            'Content-Type': 'application/json' 
          } 
        }
      )
    }
  },
}

