/**
 * Cloudflare Worker Proxy for Supabase (Edge Functions + Auth)
 * 
 * This worker proxies requests from your custom domain (e.g., api.yourdomain.com)
 * to your Supabase project (e.g., xyzabc123.supabase.co)
 * 
 * Supports:
 * - Edge Functions: /functions/v1/*
 * - Auth endpoints: /auth/v1/*
 * - All other Supabase endpoints
 * 
 * This allows you to use a custom domain without paying for Supabase Pro tier.
 */

interface Env {
  SUPABASE_URL: string
  SUPABASE_ANON_KEY: string
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, apikey, x-client-info',
  'Access-Control-Max-Age': '86400',
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS_HEADERS })
    }

    try {
      const url = new URL(request.url)
      let targetPath = url.pathname
      
      // Handle different Supabase endpoints
      // If path starts with /functions/v1, /auth/v1, /rest/v1, or /storage/v1, use as-is
      // Otherwise, assume it's an Edge Function and prepend /functions/v1
      if (!targetPath.startsWith('/functions/v1') && 
          !targetPath.startsWith('/auth/v1') && 
          !targetPath.startsWith('/rest/v1') && 
          !targetPath.startsWith('/storage/v1')) {
        // Assume it's an Edge Function - prepend /functions/v1
        const functionName = targetPath.replace(/^\//, '')
        targetPath = `/functions/v1/${functionName}`
      }
      
      // For OAuth authorize, replace redirect_uri in query params if it contains Supabase domain
      let searchParams = new URLSearchParams(url.search)
      if (targetPath === '/auth/v1/authorize' && searchParams.has('redirect_to')) {
        // redirect_to is the callback URL in our app, not the OAuth redirect_uri
        // The OAuth redirect_uri is generated by Supabase based on its configuration
        // We can't change it here, but we'll handle it in the response
      }
      
      // Build target URL
      const targetUrl = `${env.SUPABASE_URL}${targetPath}${url.search}`

      // Prepare headers
      const headers = new Headers(request.headers)
      
      // Set Supabase API key
      headers.set('apikey', env.SUPABASE_ANON_KEY)
      
      // Preserve Authorization header if present (for authenticated requests)
      // If Authorization header exists, keep it; otherwise, set Bearer token
      if (!headers.has('Authorization')) {
        headers.set('Authorization', `Bearer ${env.SUPABASE_ANON_KEY}`)
      }
      
      // Remove Host header to avoid conflicts
      headers.delete('Host')
      
      // Forward the request to Supabase
      const response = await fetch(targetUrl, {
        method: request.method,
        headers,
        body: request.body,
      })

      // Clone response to modify headers and body
      const responseHeaders = new Headers(response.headers)
      let modifiedBody: string | ReadableStream<Uint8Array> | null = null
      
      // For OAuth authorize endpoint, replace Supabase domain with proxy domain
      if (targetPath === '/auth/v1/authorize') {
        // Handle redirect responses (3xx status codes)
        if (response.status >= 300 && response.status < 400) {
          const location = responseHeaders.get('Location')
          if (location) {
            try {
              const locationUrl = new URL(location)
              // If Location contains Supabase domain in redirect_uri, replace it with proxy domain
              if (locationUrl.searchParams.has('redirect_uri')) {
                const redirectUri = locationUrl.searchParams.get('redirect_uri')!
                const redirectUriUrl = new URL(redirectUri)
                if (redirectUriUrl.hostname.includes('supabase.co')) {
                  // Replace Supabase domain with proxy domain
                  redirectUriUrl.hostname = url.hostname
                  redirectUriUrl.protocol = url.protocol
                  locationUrl.searchParams.set('redirect_uri', redirectUriUrl.toString())
                  responseHeaders.set('Location', locationUrl.toString())
                }
              }
            } catch (e) {
              console.error('Error parsing Location header:', e)
            }
          }
        }
        
        // Handle JSON responses (Supabase returns OAuth URL in JSON body)
        const contentType = responseHeaders.get('Content-Type') || ''
        if (contentType.includes('application/json') && response.status === 200) {
          try {
            const bodyText = await response.text()
            const bodyJson = JSON.parse(bodyText)
            
            // If response contains 'url' field with Supabase domain, replace it
            if (bodyJson.url && typeof bodyJson.url === 'string') {
              const oauthUrl = new URL(bodyJson.url)
              // Replace Supabase domain in redirect_uri parameter
              if (oauthUrl.searchParams.has('redirect_uri')) {
                const redirectUri = oauthUrl.searchParams.get('redirect_uri')!
                const redirectUriUrl = new URL(redirectUri)
                if (redirectUriUrl.hostname.includes('supabase.co')) {
                  // Replace Supabase domain with proxy domain
                  redirectUriUrl.hostname = url.hostname
                  redirectUriUrl.protocol = url.protocol
                  oauthUrl.searchParams.set('redirect_uri', redirectUriUrl.toString())
                  bodyJson.url = oauthUrl.toString()
                  
                  // Create new response body with modified URL
                  modifiedBody = JSON.stringify(bodyJson)
                }
              }
            }
          } catch (e) {
            // If JSON parsing fails, use original body
            console.error('Error parsing JSON response:', e)
          }
        }
        
        // Handle HTML responses (Supabase may return HTML with OAuth form)
        // Replace Supabase domain in HTML content (in redirect_uri parameters, URLs, etc.)
        if (contentType.includes('text/html') && response.status === 200 && !modifiedBody) {
          try {
            const bodyText = await response.text()
            // Replace Supabase domain in redirect_uri parameters in HTML
            // Pattern: redirect_uri=https://xyz.supabase.co/auth/v1/callback
            const supabaseDomain = env.SUPABASE_URL.replace('https://', '').replace('http://', '')
            const proxyDomain = url.hostname
            
            // Replace redirect_uri in query strings (URL-encoded and plain)
            // Pattern 1: redirect_uri=https%3A%2F%2Fxyz.supabase.co%2Fauth%2Fv1%2Fcallback (URL-encoded)
            // Pattern 2: redirect_uri=https://xyz.supabase.co/auth/v1/callback (plain)
            let modifiedText = bodyText
            
            // Replace URL-encoded redirect_uri
            modifiedText = modifiedText.replace(
              new RegExp(`redirect_uri=([^"'\s&]*)${supabaseDomain.replace(/\./g, '\\.')}([^"'\s&]*)`, 'gi'),
              (match, before, after) => {
                try {
                  // Try to decode and reconstruct URL
                  const encoded = encodeURIComponent(`${before}${supabaseDomain}${after}`)
                  const decoded = decodeURIComponent(encoded)
                  const redirectUriUrl = new URL(decoded)
                  redirectUriUrl.hostname = proxyDomain
                  const newEncoded = encodeURIComponent(redirectUriUrl.toString())
                  return `redirect_uri=${newEncoded}`
                } catch (e) {
                  // If decoding fails, try direct replacement
                  return match.replace(supabaseDomain, proxyDomain)
                }
              }
            )
            
            // Replace plain redirect_uri (not URL-encoded)
            modifiedText = modifiedText.replace(
              new RegExp(`redirect_uri=(https?://[^"'\s&]*?)${supabaseDomain.replace(/\./g, '\\.')}([^"'\s&]*)`, 'gi'),
              (match, before, after) => {
                try {
                  const redirectUriUrl = new URL(`${before}${supabaseDomain}${after}`)
                  redirectUriUrl.hostname = proxyDomain
                  return `redirect_uri=${redirectUriUrl.toString()}`
                } catch (e) {
                  return match.replace(supabaseDomain, proxyDomain)
                }
              }
            )
            
            // Also replace any direct Supabase URLs in the HTML (for display purposes)
            modifiedText = modifiedText.replace(
              new RegExp(`https?://${supabaseDomain.replace(/\./g, '\\.')}`, 'gi'),
              `${url.protocol}//${proxyDomain}`
            )
            
            // Replace Supabase domain in text content (for "to continue to" message)
            modifiedText = modifiedText.replace(
              new RegExp(supabaseDomain.replace(/\./g, '\\.'), 'gi'),
              proxyDomain
            )
            
            if (modifiedText !== bodyText) {
              modifiedBody = modifiedText
            }
          } catch (e) {
            console.error('Error parsing HTML response:', e)
          }
        }
      }
      
      // Add CORS headers to response
      for (const [key, value] of Object.entries(CORS_HEADERS)) {
        responseHeaders.set(key, value)
      }

      return new Response(modifiedBody || response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: responseHeaders,
      })
    } catch (error) {
      console.error('Proxy error:', error)
      return new Response(
        JSON.stringify({ 
          error: 'Proxy error', 
          message: error instanceof Error ? error.message : 'Unknown error' 
        }),
        { 
          status: 500, 
          headers: { 
            ...CORS_HEADERS,
            'Content-Type': 'application/json' 
          } 
        }
      )
    }
  },
}

