#!/usr/bin/env node

/**
 * Script to extract metadata from all blog post pages
 * Generates lib/blog-metadata.ts with all metadata
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { glob } from 'glob'

const blogSlugs = [
  'dead-man-switch',
  'monitor-cron-jobs',
  'cron-job-failed',
  'backup-monitoring',
  'detect-empty-backup-file-cron',
  'curl-success-but-wrong-response',
  'silent-cron-failures',
  'verify-cron-output',
  'detect-empty-backup-file',
  'cron-job-exit-code-not-zero',
  'verify-cron-job-actually-ran',
  'cron-job-returns-success-but-fails',
  'verify-backup-file-size',
  'cron-job-silent-failure-detection',
  'curl-returns-200-but-wrong-data',
  'detect-cron-job-partial-failure',
  'detect-cron-job-wrong-exit-code',
  'verify-script-output-content',
  'detect-backup-file-missing',
  'cron-job-not-executing',
  'verify-cron-job-completed',
  'detect-cron-job-skipped',
  'backup-file-zero-bytes',
  'cron-job-exit-status-check',
]

interface BlogMetadata {
  title: string
  description: string
  keywords?: string
  canonical: string
}

function extractMetadata(slug: string): BlogMetadata | null {
  const filePath = join(process.cwd(), 'app', 'blog', slug, 'page.tsx')
  
  try {
    const content = readFileSync(filePath, 'utf-8')
    
    // Extract title
    const titleMatch = content.match(/title:\s*"([^"]+)"/)
    const title = titleMatch ? titleMatch[1] : null
    
    // Extract description
    const descMatch = content.match(/description:\s*"([^"]+)"/)
    const description = descMatch ? descMatch[1] : null
    
    // Extract keywords
    const keywordsMatch = content.match(/keywords:\s*"([^"]+)"/)
    const keywords = keywordsMatch ? keywordsMatch[1] : undefined
    
    // Extract canonical
    const canonicalMatch = content.match(/canonical:\s*"([^"]+)"/)
    const canonical = canonicalMatch ? canonicalMatch[1] : `/${slug}`
    
    if (!title || !description) {
      console.warn(`Warning: Missing metadata for ${slug}`)
      return null
    }
    
    return {
      title,
      description,
      keywords,
      canonical,
    }
  } catch (error) {
    console.error(`Error reading ${filePath}:`, error)
    return null
  }
}

function main() {
  console.log('Extracting metadata from blog posts...')
  
  const metadataMap: Record<string, BlogMetadata> = {}
  
  for (const slug of blogSlugs) {
    const metadata = extractMetadata(slug)
    if (metadata) {
      metadataMap[slug] = metadata
    }
  }
  
  // Generate TypeScript file
  let output = `/**
 * Blog post metadata
 * Auto-generated by scripts/extract-blog-metadata.ts
 * DO NOT EDIT MANUALLY - run 'npm run extract-blog-metadata' to regenerate
 */

import type { Metadata } from 'next'

export interface BlogPostMetadata {
  title: string
  description: string
  keywords?: string
  canonical: string
}

export const blogMetadata: Record<string, BlogPostMetadata> = ${JSON.stringify(metadataMap, null, 2).replace(/"([^"]+)":/g, '$1:')}

export function getBlogMetadata(slug: string): Metadata | null {
  const meta = blogMetadata[slug]
  if (!meta) return null
  
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://deadmanping.com'
  const cleanBaseUrl = baseUrl.replace(/^https?:\\/\\/(www\\.)?/, 'https://')
  
  return {
    title: meta.title,
    description: meta.description,
    keywords: meta.keywords,
    openGraph: {
      title: meta.title,
      description: meta.description,
      type: 'article',
      url: \`\${cleanBaseUrl}/blog/\${slug}\`,
    },
    twitter: {
      card: 'summary_large_image',
      title: meta.title,
      description: meta.description,
    },
    alternates: {
      canonical: \`/blog/\${slug}\`,
    },
  }
}
`
  
  const outputPath = join(process.cwd(), 'lib', 'blog-metadata.ts')
  writeFileSync(outputPath, output, 'utf-8')
  
  console.log(`✅ Extracted metadata for ${Object.keys(metadataMap).length} blog posts`)
  console.log(`📄 Output: ${outputPath}`)
}

main()
